/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file icons/clearlist.png */
extern const unsigned char clearlist[];

/* created by reswrap from file icons/complete.png */
extern const unsigned char complete[];

/* created by reswrap from file icons/edititem.png */
extern const unsigned char edititem[];

/* created by reswrap from file icons/incomplete.png */
extern const unsigned char incomplete[];

/* created by reswrap from file icons/markcomplete.png */
extern const unsigned char markcomplete[];

/* created by reswrap from file icons/markincomplete.png */
extern const unsigned char markincomplete[];

/* created by reswrap from file icons/newlist.png */
extern const unsigned char newlist[];

/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file icons/quitchecklist.png */
extern const unsigned char quitchecklist[];

